### ISSUE TITLE
Infernce pipeline

### ISSUE THREAD

**Issue by abhigoku10** [wei-tim/YOWO#11]
@okankop @wei-tim  thanks for open sourcing the code base , have few queries 
1. do we have a inference pipeline to test on few sets of images or should i use "run_video_mAP_jhmdb.sh" files
2. can i test on an offline video recorded by myself  if so what is the command 
3. in your "run_video_mAP_jhmdb.sh" script file there is a param "--backbone_3d resnext101 \ 	 				--backbone_2d darknet \ "  should we pass both backbone_3d and 2d models ??
4. you have asked to download the model files right can you please specifiy in the reference folder which one to dowload since there are different models with same name
5. can we run the code on cpu , is so should we specifiy in the command prompt
thansk in advance

**Comment by abhigoku10** [comment]
@wei-tim @okankop  can you please respond to this

**Comment by okankop** [comment]
@abhigoku10 
1. Yes, please investigate the "def test(epoch)" function in file https://github.com/wei-tim/YOWO/blob/master/train.py 
2. Yes you can. This is how the training is done. Frames are read from offline recorded videos. You can write a script to test.
3. If you load a pretrained model shared in the README, you do not need to load backbones separately. If you want to make training, you need to load the backbone weights. But always you should specify which backbones you are using since the model is created accordingly.
4. You can simply download the pretrained models.
5. Yes you can run the model on cpu if you write a script accordingly.

**Comment by okankop** [comment]
I believe issue is resolved!
